spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 
  h2:
    console:
      enabled: true
      path: /h2-console
         